[postgresql]
# Sostituisci host e porta con il pooler
host = "aws-1-eu-central-1.pooler.supabase.com"   # trovi l'URL esatto in Project Settings → Database → Connection Pooling
port = 6543
database = "postgres"
username = "postgres.siwxtimwbmvnttuppnug"         # formato: postgres.<project-ref>
password = "lHUM2MERo3s6kHLd"
